# Introduction to PyTorch

### Basic PyTorch Funtions

In [105]:
# let's get familiar with some basic PyTorch funtions
import torch
# TYPO ON ORIGINAL NOTEBOOK 2x3 not 2x6
# define a float Tensor with even numbers of size 2x3 (odd numbers would be 2.*i+1.)
x1 = torch.tensor([2.*i for i in range(6)]).reshape(2,3)


# define a tensor intialized from a uniform distribution of size 2x3
x2 = torch.rand(2,3) #randn from NORMAL distribution

# inspect the shapes of the tensors
print(x1)
print(x1.shape)

print("----------------------")

print(x2)
print(x2.shape)

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
torch.Size([2, 3])
----------------------
tensor([[0.3571, 0.3358, 0.7290],
        [0.9105, 0.4581, 0.6129]])
torch.Size([2, 3])


In [91]:
# add these tensors together.
result = x1+x2
print(result)

#Perform other operations such as multiplication or division (element-wise)
multiplication = x1*x2 #element-wise, for matrix multiplication see below
division = x1/x2 #element-wise

tensor([[ 0.0585,  2.2091,  4.3491],
        [ 6.6473,  8.1663, 10.6910]])


In [92]:
# sum the total values in the resulting tensor
total_sum = torch.sum(result) #adds up all the elements of tensor, you can use argument dim= to sum in only one dimension

#get the mean value
mean_value =torch.mean(result) # same for argument dim=0 or 1, averages in 1 dimension

tensor(32.1212)


In [81]:
# dim=0 for columns dim=1 for rows
# sum across colums (use torch.sum())
col_sum = torch.sum(result, dim=0)
# sum across rows
row_sum = torch.sum(result, dim=1)

#check if size is correct
print(col_sum.shape, row_sum.shape)

torch.Size([3]) torch.Size([2])


In [82]:
# get the power of 2 of the resulting tensor
result_pow= result**2

In [83]:
# compute the element-wise and matrix product of these two tensors.
x3 = torch.rand(3,2)
print(x3)
print()

# ONLY VECTORS
#torch.dot() (1D tensors)
#torch.dot(x1,x2) will return error

#ELEMENT_WISE TENSOR MULTIPLICATION
# * == torch.mul()
print(x1 * x2)

# tensor times other (equivalent to element wise)
print(torch.mul(x1,x2))

# TENSOR PRODUCT
# @ == torch.matmul()

#matmul ->  (depends on dimensionality)
# print(torch.matmul(x1,x2)) error -> not right size
print(x1 @ x3)
print(torch.matmul(x1,x3))

tensor([[0.4360, 0.2179],
        [0.2403, 0.8066],
        [0.1585, 0.5551]])

tensor([[0.0000, 1.4758, 3.8765],
        [4.5179, 6.5556, 0.2976]])
tensor([[0.0000, 1.4758, 3.8765],
        [4.5179, 6.5556, 0.2976]])
tensor([[ 1.1145,  3.8336],
        [ 6.1233, 13.3115]])
tensor([[ 1.1145,  3.8336],
        [ 6.1233, 13.3115]])


In [102]:
# can you compute the dot product betweeen x1 and x2? what if you use the reshape (or view) function first?)
## dot product not direclty -> only for 1D matrices (i.e. vectors, reshape to 1x6 first then compute dot product) see below:
x1_reshape = x1.reshape(6,)
x2_reshape = x2.reshape(-1,)
print(x1_reshape.shape,x2_reshape.shape)
dotprod = torch.dot(x1_reshape,x2_reshape)
print(dotprod)

torch.Size([6]) torch.Size([6])
tensor(13.9383)


In [88]:
# convert the PyTorch Tensor to a numpy array, and then back from numpy to PyTorch using .numpy() and .from_numpy() torch functions
np_result = x1.numpy()
pytorch_from_np = torch.from_numpy(np_result)
print(np_result)
print(pytorch_from_np)

[[ 0.  2.  4.]
 [ 6.  8. 10.]]
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
